services:
  backend:
    build: ./flask_app
    ports:
      - "5000:5000"
    volumes:
      - flask_db_data:/flask_app/data  # Mount point for SQLite database
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  flask_db_data:    # Define the volume