services:
  backend:
    build: ./flask_app
    expose:
      - "5000"
    volumes:
      - flask_db_data:/flask_app/data
    environment:
      - FLASK_ENV=production

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

volumes:
  flask_db_data: